### ISSUE TITLE
React Knowledgeable #30 - May 24

### ISSUE THREAD

**Issue by KenLSM** [Shopee/react-knowledgeable#100]
# React Knowledgeable Week 30

🗓 Date: 18:00, Friday, 24 May
🗺 Location: 2nd Floor Sharing Space

## Open slot for talk

June 7.

**Comment by wgao19** [comment]
Pre
---
- Week 30, self intro to new interns
- [Fortnightly updates on React](https://github.com/react-knowledgeable/newsletter/blob/master/week-30.md)

Talks
---
- Introduce rule for bey timer hooks show and tell
    - You tell us how much time you need
    - Lady SingaporeCSS creator of bey-timer will bey you off the stage if you go over time
- Got four tells, in following order:
    - lihau
    - adriel
    - tvan
    - gaowei (if got time)


Post
---
- Call for volunteer to JSConf Asia mainly to interns
- Next week is Chenchen sharing about Google IO
- Next open spot to speak is June 7, which is right next next week, I know you all won’t do it, then we’ll have some fun activities for the day
