### ISSUE TITLE
The Difficulty of Going Green

### ISSUE THREAD

**Issue by heyjiawei** [Shopee/react-knowledgeable#105]
The Difficulty of Going Green ⛰️(est. 20 mins)

Speaker
---
Jia Wei

Intro
---
This talk will focus on the challenges and complexity of going green, and address the known and unknown impact of not doing so. Rather than green-washing everyone, this talk aims to explain the rationale of why Going Green doesn't take off well and the consequences of continuing with our current consumption behaviour.

Ready by
---
7th June 2019

**Comment by wgao19** [comment]
Hiiii I think the partial talk you did at the board game was great. Let's slot you in for June 7 :)
Thank you for preparing for the talk!

**Comment by wgao19** [comment]
Hey @heyjiawei we forgot to update your slides here.

**Comment by heyjiawei** [comment]
Do you need the link here?
https://slides.com/chongjiawei/the-difficulty-of-going-green

**Comment by wgao19** [comment]
Yah that's good :) Thank you.
