### ISSUE TITLE
Website for react-knowledgeable

### ISSUE THREAD

**Issue by tanhauhau** [Shopee/react-knowledgeable#11]
Can I create a landing page for react-knowledgeable, and embed all our sharings + videos?

**Comment by wgao19** [comment]
Sure! Let's do that :)

**Comment by KenLSM** [comment]
Does https://reactknowledgeable.org/ count as the website? Hhaha

**Comment by wgao19** [comment]
Yes. Although, that is a separate cause. I guess we should close this ticket then.
