### ISSUE TITLE
✏️ #LearnInPublic

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#114]
Speaker
---
@sw-yx 

Intro
---
Shawn ([@swyx](https://twitter.com/swyx)) will be sharing with us about [Learn in Public](https://gist.github.com/sw-yx/9720bd4a30606ca3ffb8d407113c0fe5).

**Comment by wgao19** [comment]
Questions
---

@Tzyinc:
Writing a blog/writeup of my learning journey is incredibly exhausting, on top of doing side projects, in most cases i would do the side project then feel that what i have done is not worthy of any writeup, not even worth the energy to write, how do we channel this energy and enthusiasm into the process of writing things and not making things?

for "specialising in the new", whats a good place to find out about the "new" that we can specialise in? I have a few RSS feeds that i follow but they usually talk about old stuff and how to be better at them


@tanhauhau:
can you share a bit more of your daily routine, and weekend routine, what do you do in his free time, what exact thing did you do to learn and improve in yourself.

@JennieJi:
Curious about your Learn in Public achievements in this year

**Comment by wgao19** [comment]
@wgao19
- What are you learning now?
- How do you pick your subjects to learn?
- What are some subjects or topics that non cs major miss but are important to understanding?
- What is your proportion of time spent in the actual learning vs creating content? Is there a healthy or optimal ratio?
- How do you manage your time?
- What do you think is the most meaningful among all your contributions?

**Comment by wgao19** [comment]
[Video](https://engineers.sg/video/learn-in-public-react-knowledgeable--3420) (recorded by [engineers.sg](https://engineers.sg) ❤️🦄)

**Comment by sw-yx** [comment]
so embarrassing 😂

**Comment by wgao19** [comment]
Wait, why? That was a great talk!
