### ISSUE TITLE
🧙🏻‍♂️ Time Tracking

### ISSUE THREAD

**Issue by kenrick95** [Shopee/react-knowledgeable#116]
Speaker
---
me

Intro
---

Did you ever spend a week feeling unproductive? did nothing useful? being interrupted constantly? didn't code as much as expected? too many meetings? 

Do you want the situation to improve?

Just like any "performance improvement", the first step is to measure your current state.

So... presenting to you: Time Tracking ✨ 

I've been tracking my time since March 2018 and will share the tools and practice that I do to track my time and automate the chores in time tracking. I've put this as a Confluence page in my personal space, but decided to share as a talk as suggested by Master Sun.

---
- Estimated duration:  around 20 mins I guess?
- Ready by: end June 2019
- Needs dry run:  Y

**Comment by wgao19** [comment]
Great proposal I seriously need this <3
Please let us know once you're ready then we can go for dry run then delivery :))))

**Comment by kenrick95** [comment]
- [Time tracking slides](https://docs.google.com/presentation/d/150rD_weKAlDNdY5h21igWy2ALJy0YCO-6L9C1iEa56c/edit?usp=sharing)
- [Time tracking confluence page](https://confluence.shopee.io/display/~kenrick@seagroup.com/Time+Tracking)

**Comment by wgao19** [comment]
Awesome, thank you! And your speaker sticker is on your table now :)))

**Comment by wgao19** [comment]
A few resources mentioned
- [Scrum](https://trello.vince.run/scrum/) This is the main tool to keep track of the time spent. This is the most important power-up.
- [Booklet](https://trello.vince.run/booklet/) This is the tool to use at the end of the week to export out the list of tasks. Enable this if you have Trello Gold.
- [Butler Bot](https://butlerfortrello.com/) A helper bot to create recurring cards and also to move the finished cards to Archive board. Enable this if you have Trello Gold.
