### ISSUE TITLE
React Knowledgeable #37 - July 26, 2019

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#121]
# React Knowledgeable Week 36

🗓 Date: 18:00, Friday, July 12, 2019
🗺 Location: 2nd Floor Sharing Space
🦄 Host: @wgao19 

## RK this week

- Open slot for talk: **Aug 2**
- React updates by @wgao19, [thread](https://twitter.com/reknowledgeable/status/1145636047079890944?s=20)

Build your own bundler - Overview, #107 
---
> A year ago, when we are in a much smaller team, I shared about https://git.garena.com/tanlh/cepture, slides
> It's about how to build your own bundler.
> A year later, I've learned a lot deeper personally.
. Maybe it's time to go deeper and more elaborate into each steps, dissecting what a bundler is
> And also, because I see dr. t1ger is going around series of interesting talk. I want to improve on my explaining skills. and knowledge transfers to the new hires

♻ Reduce, reuse, recycle in Singapore, #110
---
> After Jiawei's talk on the motivation of going Green, we'll have @JennieJi share with us some practical steps towards greenness in Singapore 🇸🇬

---

<details>
 <summary>Checklist</summary>

- [x] submitted request for cafe booking
- [ ] venue confirmed & additional booking cancelled

</details>

**Comment by KenLSM** [comment]
@JennieJi  Will you be able to share the react upgrades for this week? I think @wgao19 will be missing this event this week.

**Comment by KenLSM** [comment]
♻ Reduce, reuse, recycle in Singapore, #110 wasn't presented due to overrun. Will reschedule!
