### ISSUE TITLE
👾AI for FE 👾

### ISSUE THREAD

**Issue by Tzyinc** [Shopee/react-knowledgeable#122]
👾AI for FE 👾
Breaking down the illusion of difficulty in AI

Speaker
Ten Zhi Yang

Intro
During the hackathon some friends I knew expressed regrets at not learning about AI during their school time. I hope that by the end of the talk I can tear down the difficulty of AI with some easily accessible libraries, and explain some "big picture" concepts in human language

---
- Estimated duration:  🧙🏻‍♂️ 30 mins
- Ready by: 12 july 2019
- Needs dry run:  probably

**Comment by wgao19** [comment]
Sweet. You can decide whether you feel comfortable or prefer running it. I think July 19 prep hour is open. Would like to schedule this talk on July 26 regardless.

**Comment by wgao19** [comment]
Related posts:
- https://tenzhiyang.com/2019-07-31-ai-for-fe/
- https://tenzhiyang.com/2019-08-01-ai-for-fe-2/

**Comment by Tzyinc** [comment]
Blog post for my friday talk here: https://blog.tenzhiyang.com/2019-07-31-ai-for-fe/
demos here: https://httpserve.tenzhiyang.com/
source code for demos here: https://github.com/Tzyinc/blog-http-server
slides here: http://slides.com/tzyinc/ai-for-fe/
