### ISSUE TITLE
🍓Getting to know CSS Border radius

### ISSUE THREAD

**Issue by SmokinClove** [Shopee/react-knowledgeable#125]
Speaker
---

Hi, this is Van. i decided to be a self declared CSS artist about 2 weeks ago, and having a lot of fun fulfilling this self bestowed mission turning CSS in and out, and basically testing both my own and CSS' limits.

About the talk
---
This talk is all about border-radius in CSS, or what i think are the less known use cases of this property.

- Estimated duration: ⚡️ 7 mins
- Ready by: End of July
- Needs dry run: いいえ、ありがとうごさいます

**Comment by wgao19** [comment]
Hey @SmokinClove could you please update links for this talk?

**Comment by SmokinClove** [comment]
> Hey @SmokinClove could you please update links for this talk?

Updated in the description!
