### ISSUE TITLE
🕸 Earley algorithm - a context free parser

### ISSUE THREAD

**Issue by JennieJi** [Shopee/react-knowledgeable#204]
speaker
---
@JennieJi 

intro
---
Give it a proper set of grammer, and it can parse any languages for you, how did an algorithm created on 1968 did that?

resources
---

Scheduling
---
- Estimated duration:  25 mins
- Ready by: 5 June
- Needs dry run: No

**Comment by wgao19** [comment]
great!

u sure about time? sounds like a well deserved topic for an in-depth sharing

**Comment by JennieJi** [comment]
@wgao19 it's actually not that complicated, but I will update u in advance after I got my slides draft done

**Comment by wgao19** [comment]
Great, looking forward!

**Comment by JennieJi** [comment]
😢  update to 25min

**Comment by JennieJi** [comment]
Slides: https://docs.google.com/presentation/d/18C9ZO9H3mO50Mp6nHnrNGhfI3FP5-p8xGmZc0AGYIW0

**Comment by JennieJi** [comment]
And blog version: https://dev.to/jennieji/context-free-language-parsing-with-earley-algorithm-2kp3

**Comment by wgao19** [comment]
Thanks for the sharing! Here's the link to the video: https://youtu.be/5VjjlDJxRy4
