### ISSUE TITLE
🐈 WNB - What Nonsense is Boxocat

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#207]
speaker
---
@wgao19 

intro
---
I have a stress relieving, nonsense project to share about. Minimally technical, mostly my brain rubbish.

- React: 1%
- CSS: 1%
- JavaScript: 1%
- nonsense: 99.99%

Please bring your cat.

resources
---
- [slides](https://slides.com/wgao19/boxocat/)
- [@huijing's neue pet sne](https://5b9rg.csb.app/?blueprint=000000000000000000001c2o3c6o736w736w5c0r5k4b65626w6y6o3e73723j6o)
- [code sandbox](https://codesandbox.io/s/boxocat-5b9rg)
- [video](https://youtu.be/KdNPia4OrNo)

Scheduling
---
- Estimated duration: ⚡️ 10 mins

**Comment by tanhauhau** [comment]
🥡 🐈

**Comment by wgao19** [comment]
> 🥡

is this cat food
