### ISSUE TITLE
🗯️ Thoughts on a self-imposed hackathon

### ISSUE THREAD

**Issue by Tzyinc** [Shopee/react-knowledgeable#208]
speaker
---
Tenzy

intro
---
I'm stuck technically on #200 but then I recently built https://twatter.tenzhiyang.com , and I feel I can talk on that instead, do let me know if this topic is too boring

[Recently on cassidoo's newsletter](https://buttondown.email/cassidoo/archive/95ad0226-1271-49f7-88bb-42cb0283ee38) the problem of the week was to create a twitter clone, and I wasn't going to end my solving-one-problem-every-week-streak break, so I decided to build it, and learn how to use svelte and sapper in the process. I will cover my thought process, learning points about development on svelte vs react and touch on how I built a working but simple backend via lokijs+nodejs+express.

resources
---
https://twatter.tenzhiyang.com

- slides
https://slides.com/tzyinc/thoughts-on-a-self-imposed-hackathon/#/
- video
- more links
https://github.com/Tzyinc/Twatter
https://twatter.tenzhiyang.com/

//links in the slide
https://cassidoo.co/newsletter/
https://gist.github.com/Rich-Harris/0f910048478c2a6505d1c32185b61934
https://github.com/sw-yx/ssg

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by: 29 may
- Needs dry run: no

**Comment by wgao19** [comment]
video will be up at https://youtu.be/Mut4F3C_dv8

**Comment by wgao19** [comment]
Video going public this morning!
