### ISSUE TITLE
🎒 monorepo and our webpack 

### ISSUE THREAD

**Issue by tanhauhau** [Shopee/react-knowledgeable#210]
speaker
---
@tanhauhau 

intro
---
The story of how we patch up monorepo in our monolithic repo. How we patch up our webpack, how we thought we've patched up webpack, and how we patch more patches to make it more "maintainable".

(Hopefully I'm gonna make it as a light talk,  yet something to take away at the end of the day.)

resources
---

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by: 29 May
- Needs dry run: `true`

**Comment by KenLSM** [comment]
@tanhauhau we have a slot open next week, can we have this talk?

**Comment by tanhauhau** [comment]
@KenLSM yes please!!

**Comment by wgao19** [comment]
Hello @tanhauhau since this is ready I'm scheduling it to go with RK 81 on July 10

**Comment by wgao19** [comment]
question: do you want dry run?

**Comment by tanhauhau** [comment]
yes. lets have dry run.

**Comment by wgao19** [comment]
Thanks for this sharing! [link to live stream - start of this video](https://www.youtube.com/watch?v=2KWsRsuis_Q&t=1311s)
