### ISSUE TITLE
Is it possible to block users from leaving a page on a single page app? 🤔

### ISSUE THREAD

**Issue by heyjiawei** [Shopee/react-knowledgeable#214]
Is it possible to block users from leaving a page on a single page app?🤔

speaker
jiawei

intro
I'll share about how history blocking is possible on a Single Page App, but with limitations

resources
---

Scheduling
---
- Estimated duration: ⚡️ 7 mins / 🧙🏻‍♂️ 30 mins
- Ready by: I'll try to get it done 28th Aug 🙇‍♀️ 
- Needs dry run:

**Comment by wgao19** [comment]
yay you're finally convinced to share about this!

> 28th Aug

really, no typo here?

**Comment by heyjiawei** [comment]
yep 😅

**Comment by wgao19** [comment]
that's a very specific but faraway date 😅

**Comment by heyjiawei** [comment]
Slides here: https://slides.com/chongjiawei/is-it-possible-to-block-users-from-leaving-a-page-on-a-single-page-app

**Comment by wgao19** [comment]
Thank you for this sharing!
