### ISSUE TITLE
🍉 The Obscurities of Bézier Curves Explained to My Computer Engineer Friends

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#216]
speaker
---
@wgao19 

intro
---
Bézier Curves are one of the most fundamental computer graphics tools. They even grant their presence in [CSS easing functions](https://www.w3.org/TR/css-easing-1/). Why some magic numbers can define curves? How to break a Bézier curve into smaller curves without computing more numbers? How to join two curves?

Its recursive nature gives it an interesting implementation with React. This gives it a marginal connection with our podium (_React_ Knowledgeable) and @SingaporeCSS (with CSS easing functions, I guess).

The computing (algebraic) and intuitive (geometric) connections here are the most amazing aspects of the marriage between math and computing that I hope I can shed some lights on.

resources
---
_to be updated_

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30+ mins

**Comment by JennieJi** [comment]
😍looking forward to this

**Comment by huijing** [comment]
![515753796228612107](https://user-images.githubusercontent.com/1461498/84588524-c09c9b80-ae5a-11ea-96f1-88862acddd85.png)
