### ISSUE TITLE
👾 Prioritizing Technical Debt

### ISSUE THREAD

**Issue by miccheng** [Shopee/react-knowledgeable#219]
speaker
---

@miccheng

intro
---
Michael Cheng is a full stack developer with more than 10 years of experience in building dynamic websites. He is a Zend Certified Engineer/Trainer in PHP development. He currently does Ruby & Go Lang.

He runs the Singapore PHP User Group, co-founded the iOS Dev Scouts and is the organiser of PHPConf.Asia. He also runs Engineers.SG, a not-for-profit community initiative to document and archive the tech and startup scene in Singapore. His latest passion project is JuniorDevSG, a support group for junior developers in Singapore. Michael is currently a Lead Software Engineer with GovTech Singapore.

Resources
---

- Slides: https://docs.google.com/presentation/d/1Gy_lpD_mjdqpFFx40v19E1sEPXqy5SJSnDwWuLkktz0/edit?usp=sharing

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins

**Comment by tanhauhau** [comment]
Wow senpai!

**Comment by miccheng** [comment]
Here's the link to my slide: https://docs.google.com/presentation/d/1Gy_lpD_mjdqpFFx40v19E1sEPXqy5SJSnDwWuLkktz0/edit?usp=sharing

**Comment by wgao19** [comment]
@miccheng thank you for this sharing! video will be up tmr, link here: https://youtu.be/iPyrczNATUE
