### ISSUE TITLE
🥺 How to Prioritize Tasks?

### ISSUE THREAD

**Issue by kenrick95** [Shopee/react-knowledgeable#220]
speaker
---

Kenrick

intro
---

You know me ;)

resources
---

- Slides: https://docs.google.com/presentation/d/11VJgwHvQZ5GZ3IM5jdqLEtAxL1svM72W67ubWe45R8Y/edit?usp=sharing 

Scheduling
---
- Estimated duration: ⚡️ 5-10 mins
- Ready by:
- Needs dry run:

**Comment by wgao19** [comment]
Thanks for this sharing!
