### ISSUE TITLE
🌈 all colours no javascript

### ISSUE THREAD

**Issue by huijing** [Shopee/react-knowledgeable#221]
speaker
---
@huijing

intro
---
a talk about colours. sprinkled with some css. no javascript though. ¯\\\_(ツ)_/¯

resources
---
[slides](https://huijing.github.io/slides/85-css-colours/)

Scheduling
---
- Estimated duration: between ⚡️ 7 mins and 🧙🏻‍♂️ 30 mins ?
- Ready by: 19 Jun 2020
- Needs dry run: no

**Comment by wgao19** [comment]
thank you for this sharing :)
