### ISSUE TITLE
React Knowledgeable 81 - July 17, 2020

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#224]
## React Knowledgeable Week 81

🗓 Date: 18:00, Friday, July 17, 2020
🦄 Host: @wgao19 
🌐 Live stream: https://youtu.be/2KWsRsuis_Q

**🎒 monorepo and our webpack #210**

> The story of how we patch up monorepo in our monolithic repo. How we patch up our webpack, how we thought we've patched up webpack, and how we patch more patches to make it more "maintainable".

**📌 Pinpointing a bug 🐞 in Firefox 🦊 #226**

> My journey on pinpointing an interesting bug in Firefox without knowing how Firefox code works.

<details>
 <summary>Checklist</summary>

- [x] create YouTube live stream
- [x] update cal inv information (content, venue, live stream url, zoom lounge invitation)

</details>

**Comment by kenrick95** [comment]
Note that 10 July is Polling Day, declared as public holiday 🌈 

[Sauce](https://www.mom.gov.sg/newsroom/press-releases/2020/0624-public-holiday-on-polling-day---10-july-2020)

**Comment by wgao19** [comment]
oh what, so, are we working on that day?

**Comment by kenrick95** [comment]
It's mandatory for Singaporeans to vote, how can they work 😆
