### ISSUE TITLE
🚀 Quaternions & WebGL 

### ISSUE THREAD

**Issue by chris-nee** [Shopee/react-knowledgeable#225]
speaker
---
Chris Ling

intro
---
Sharing on an experience working with webGL libraries and how to navigate through them using quaternions

resources
---
- [Slides](https://drive.google.com/file/d/1v-BfbTasJgAxYLwDDd7otDU09MzALUfj/view?usp=sharing)
- Video 
   - [How to Visualise quaternions](https://www.youtube.com/watch?v=d4EgbgTm0Bg)
- Links to libraries
   - [CesiumJS](https://cesium.com/cesiumjs/)
   - [ThreeJS](https://threejs.org/)

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by: 31st July 2020
- Needs dry run: Yes

**Comment by wgao19** [comment]
Hey @MyFrailFist thanks for proposing this and noted on the ready date. Since July 31 is a public holiday (also Harry Potter's birthday), we may need to move it to a day nearby, like the Wed of the week, is this ok with you?

**Comment by chris-nee** [comment]
Hi @wgao19 I didn't know about the birthday 😂 but yes wednesday is fine for me too

**Comment by wgao19** [comment]
Thanks for this sharing! [link to video with timestamp](https://youtu.be/ICBZLAPdgOo?t=1151)
