### ISSUE TITLE
📌 Pinpointing a bug 🐞 in Firefox 🦊

### ISSUE THREAD

**Issue by Ang-YC** [Shopee/react-knowledgeable#226]
speaker
---
@Ang-YC

intro
---
My journey on pinpointing an interesting bug in Firefox without knowing how Firefox code works

resources
---

Scheduling
---
- Estimated duration: ⚡️ 7-10 mins
- Ready by: 15 Jul
- Needs dry run: `true`

**Comment by wgao19** [comment]
Thanks for this sharing! [link to live stream - start of this sharing](https://www.youtube.com/watch?v=2KWsRsuis_Q&t=372s)
