### ISSUE TITLE
RK #82 - 🐤 Talk with Shawn about The Coding Career Handbook - July 24, 2020

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#227]
## React Knowledgeable Week 82

🗓 Date: 18:00, Friday, July 24, 2020
🦄 Host: @KenLSM @tanhauhau 
🌐 Live stream: https://youtu.be/50GKF08jLxo

@tanhauhau interviews our friend @sw-yx about his newly published book [The Coding Career Handbook](https://learninpublic.org/).

<details>
 <summary>Checklist</summary>

- [ ] create YouTube live stream
- [ ] update cal inv information (content, venue, live stream url, zoom lounge invitation)

</details>

**Comment by swyxio** [comment]
yay

**Comment by wgao19** [comment]
Thank you @tanhauhau @sw-yx for sharing this! Our first podcast-like sharing 😄

**Comment by swyxio** [comment]
this was super fun, thank u very much for inviting me!
