### ISSUE TITLE
🐛Inside the dangerous bug zoo - case studies on web vulnerabilities

### ISSUE THREAD

**Issue by senyuuri** [Shopee/react-knowledgeable#228]
Speaker
---
@senyuuri from Sea Security Team. We hack Shopee for a living : )

Intro
---
Many believe the web had become much more secure over the years. But in reality? That's so not true.
On behalf of our _beloved_ security team, we'd love to re-introduce many old yet familiar bugs (e.g. XSS, CSRF, WebSocket issues) and show how they managed to survive in today's modern web.

⚠️ Caution: This talk contains real bugs that may bite you at work. Welcome to the dangerous bug zoo : )

Resources
---
WIP

Scheduling
---
- Estimated duration:  🧙🏻‍♂️ 30 mins
- Ready by: 7th Aug 2020
- Needs dry run: Nope

**Comment by tanhauhau** [comment]
Wowwwww

**Comment by wgao19** [comment]
looking forward! will contact you later regarding scheduling

**Comment by JennieJi** [comment]
> We hack Shopee for a living : )

love this self intro

**Comment by senyuuri** [comment]
Thanks guys! Really love this community vibes. Looking forward to meeting you

**Comment by wgao19** [comment]
Hey @senyuuri thanks for this sharing, please share again!
