### ISSUE TITLE
👩🏻‍🏫 Two people are lying #2

### ISSUE THREAD

**Issue by KenLSM** [Shopee/react-knowledgeable#232]
Speaker
---
Host: @KenLSM 
Players: 
- [x] @aaron-maslim
- [x] @tanhauhau 
- [ ] maybe you?

Intro
---
#### Rules of the game
- 3 people participate in the game
- it's an improvisational game

#### Before each session
- each participant will be given one Wikipedia article of interest

#### During each session
- the host will choose one of the articles
- the host will ask questions to participants to facilitate discussion of the topic
- as n-1 participants don't know anything about the topic, they will have to converse/bluff/improvise with the host as if their topic was chosen

#### After each session
- audiences will be voting to determine whose topic was chosen

Resources
---
[Matt and Tom](https://www.youtube.com/watch?v=3UAOs9B9UH8) and friends playing the game

Scheduling
---
- Estimated duration: 10 mins per game set, may have more game set
- Ready by:
- Needs dry run:

**Comment by tanhauhau** [comment]
Li Hau 🤚 

I've played this before, if too many ppl playing, okay to give newer ppl chance to play

**Comment by aaron-maslim** [comment]
Aaron here, same as above.

**Comment by KenLSM** [comment]
Game didn't happen as we didn't have enough participants this round. Will call for another round in end of Q4. Thanks @aaron-maslim @tanhauhau for giving your 🤚.
🙏🙏🙏
