### ISSUE TITLE
Google Chrome Summit 2018

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#35]
## Speaker

_Kenrick_ @kenrick95

## Intro

Kenrick and Lihau attended the Google Chrome Summit 2018. They also represented Shopee to share about our work on AMP. We'll hear about their bring backs from the conference.

## Links

React Knowledgeable Week 9, #33

**Comment by kenrick95** [comment]
Today's slide: https://docs.google.com/presentation/d/1hKJ71SGLGAsOgvaYZuIZY7IvJDPVYC7S2CGiFkW7rJk/edit?usp=sharing

**Comment by wgao19** [comment]
Link to video: https://www.youtube.com/watch?v=Qu0nhs-LIIY
