### ISSUE TITLE
⚡️ Set A Little Goal, and Achieve It

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#39]
Speaker
---
**Jennie Ji @jennie.ji**

Intro
---
( Speaker profile )
> If you haven’t figured, Jennie the first girl dev in Shopee, has many more other aspects of her life. To list a few, she has passed Japanese N5, lives a minimalist lifestyle, is an amateur ocean photographer, and is (probably most known in our team as) a pedi certified rescue diver. How does she achieve so many goals in her life aside from being an effective developer? She’ll share her secret in this talk.

**Comment by wgao19** [comment]
Hey @JennieJi 
Thank you for this inspiring sharing! 

For reference of today's dry run, why don't we add some personalized sharing to the topic. i.e., how is pomodoro timer effective to you, on what tasks do you use it for, do you and your husband share the same 25 mins on your tasks at home, etc?

As another example, I remember at home you had a lot of labels when you were learning Japanese. I thought that was quite interesting. I think you can somehow add those personal stories into your talk, to make it more lively :) :)

( Those are just examples, please do not let your imagination limit to the list above. :)

**Comment by JennieJi** [comment]
Oops, in the end I removed pomodoro timer part to tell more story of mine this time.
I may try to talk about these next time.
