### ISSUE TITLE
⛰️The beautify things in Nintendo Gameboy

### ISSUE THREAD

**Issue by KenLSM** [Shopee/react-knowledgeable#43]
Speaker
---

@KenLSM 
Intro
---

Look into the design of the Nintendo Gameboy. Discover how the Gameboy hardware was designed, and admire the progress that technology have made.

Ready by
---

30 November 2018

Dry run
---
[Dec 7](https://github.com/Shopee/react-knowledgeable/projects/1#card-15159471)
[Jan 4](https://github.com/Shopee/react-knowledgeable/projects/1#card-16067713) -- with further recommendation

**Comment by wgao19** [comment]
Moved to [Dec 7 dry run](https://github.com/Shopee/react-knowledgeable/projects/1#card-15159471) :) :) :)

**Comment by KenLSM** [comment]
Moved to [Jan 4 2019 dry run](https://github.com/Shopee/react-knowledgeable/projects/1#card-16067713)

**Comment by KenLSM** [comment]
Recommendations:
- tune down on Processor functions
- add walkthrough on bootstrap code
- add OAM rendering (+ sprites blinking)

**Comment by wgao19** [comment]
Hi @KenLSM  could you please add link to your slides?

**Comment by KenLSM** [comment]
Done
