### ISSUE TITLE
⚡️A Paradox

### ISSUE THREAD

**Issue by Matherunner** [Shopee/react-knowledgeable#45]
Speaker
---

@Matherunner

Intro
---

A little paradox that seems to defy common sense.

Ready by
---

7 Dec 2018

**Comment by wgao19** [comment]
Hiiii @Matherunner thanks for signning up! What about Dec 13 6pm for dry run?
And @pedi would you mind following up on the permission issue? We need permission to add labels? Doesn't make sense to me leh. Anyway if this is the case could you please add new joiners to our organization?

**Comment by Matherunner** [comment]
Should be fine with that date.

There's no button for me to add a label:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/2558060/49266147-edaf7600-f48f-11e8-9c56-3c2d1e9782df.png">

In a repo I have control over, I can see the button:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/2558060/49266160-f902a180-f48f-11e8-9542-b2dcb0d0ba16.png">

**Comment by wgao19** [comment]
Hmm interesting, thanks for the input!

**Comment by wgao19** [comment]
Links
---
- [Slides](https://drive.google.com/file/d/1OkI61WqqqJrJ6smqqVrbTURqFtmFgBsP/view?usp=drivesdk)
