### ISSUE TITLE
⛰️ CSS in JS 

### ISSUE THREAD

**Issue by KenLSM** [Shopee/react-knowledgeable#46]
Speaker
---

Minh

Intro
---

Ready by
---

Dec 7

Links
---
[📹](https://www.youtube.com/watch?v=wInNaXzk2_8)
[Slides](https://mattermost.garenanow.com/files/6iop9yuxcinr38et9b63rp7zyw/public?h=FjtU8HXH-k2HNKfE4vPpM4RCQMgNmtj5ETlsGqliN9A)

**Comment by wgao19** [comment]
Moved to [Dec 21 dry run](https://github.com/Shopee/react-knowledgeable/projects/1#card-15321143) upon request.

**Comment by KenLSM** [comment]
This was postponed to [Jan 4 2019dry run](https://github.com/Shopee/react-knowledgeable/projects/1#card-16067713) upon request
