### ISSUE TITLE
Continuation-passing style and yin-yang puzzle

### ISSUE THREAD

**Issue by KenLSM** [Shopee/react-knowledgeable#47]
Speaker
---

T1ger

Intro
---

Ready by
---

Dec 13

**Comment by wgao19** [comment]
oh shit, duplicated. Let me close the other one.

**Comment by wgao19** [comment]
Need to reschedule this one to another time. @t1ger-0527 can let us know when you will be back & be ready for the talk?

**Comment by wgao19** [comment]
Hey @t1ger-0527 any updates for this talk?

**Comment by wgao19** [comment]
this zombie dies yielding to a more interesting problem
