### ISSUE TITLE
Tail Call Optimization in ECMAScript 6

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#49]
The [tail call](https://en.wikipedia.org/wiki/Tail_call) optimization of functional programming languages is quite interesting. As we know JavaScript added tail call optimization in ES6 too. This is also grandpa Doug Crockford's favorite ES6 feature addition.

Can someone please give a talk on this topic?

Some References
---
- [Tail call optimization in ECMAScript 6](http://2ality.com/2015/06/tail-call-optimization.html)
- [What's tail call](https://en.wikipedia.org/wiki/Tail_call)

**Comment by tanhauhau** [comment]
i can prepare this

**Comment by wgao19** [comment]
Closing because no proper followup is heard.
