### ISSUE TITLE
⚡️Underwater

### ISSUE THREAD

**Issue by JennieJi** [Shopee/react-knowledgeable#53]
Speaker
---

Jennie

Intro
---

What I do and see in diving, and short introduction of how to start.

Ready by
---

No dry run, talk on 11 Jan?

**Comment by wgao19** [comment]
Can let us know how long is the video?

**Comment by JennieJi** [comment]
@wgao19 5:45

**Comment by wgao19** [comment]
Yea sure let's do it.
