### ISSUE TITLE
⛰ Thoughts on redux usage

### ISSUE THREAD

**Issue by JennieJi** [Shopee/react-knowledgeable#55]
Speaker
---

Jennie

Intro
---

- Issues we are facing or faced on current reducer structure
- Ideas about better reducer structure design

Ready by
---

1 March

**Comment by JennieJi** [comment]
Hi @wgao19 , my slides are ready, but I find too much to talk so I need to upgrade it to feature talk. Do we have feature talk slot on 8 March?

**Comment by wgao19** [comment]
Yes we do. Since you are ready, would you like to dry run this Friday, Mar 1 instead?

**Comment by JennieJi** [comment]
yes pls
