### ISSUE TITLE
⛰️ A Timezone Bug

### ISSUE THREAD

**Issue by Matherunner** [Shopee/react-knowledgeable#61]
Speaker
---
@Matherunner

Intro
---
It all started with a bug report. Assumptions you have about timezones will be challenged.

Ready by
---
Late February? Early March?

**Comment by wgao19** [comment]
Will check back with you on a dry run date after CNY.

**Comment by wgao19** [comment]
Hey @Matherunner  are you still working on this talk?

**Comment by Matherunner** [comment]
Yes I’m half way through creating the slides

**Comment by wgao19** [comment]
Hi @Matherunner any updates for this talk?

**Comment by Matherunner** [comment]
I should be ready now. Though I'll need to change this to a feature talk because there's quite a bit to talk about.

**Comment by wgao19** [comment]
Sounds good :) Would you like to dry run next Friday (Mar 8)?

**Comment by Matherunner** [comment]
Yup I can do it next Friday.
