### ISSUE TITLE
⚡️Developer Experience vs User Experience

### ISSUE THREAD

**Issue by tanhauhau** [Shopee/react-knowledgeable#62]
Speaker
---

Intro
---
Developer Experience VS User Experience
Food for thought about DX vs UX, from the article (https://alistapart.com/article/breaking-the-deadlock-between-user-experience-and-developer-experience)

Ready by
---
~~🤷‍♂️~~  End of January 

Slides
---
https://slides.com/tanhauhau/dx-vs-ux (WIP)

**Comment by wgao19** [comment]
What does 🤷‍♂️ supposed to mean?

**Comment by tanhauhau** [comment]
Probably end of January. [slides wip here](https://slides.com/tanhauhau/dx-vs-ux)

**Comment by wgao19** [comment]
Sure, let us know when you have a ready date for dry run.

**Comment by wgao19** [comment]
Closing because no proper followup is heard.
