### ISSUE TITLE
🐧 How to Linux on Windows

### ISSUE THREAD

**Issue by ynov** [Shopee/react-knowledgeable#63]
Speaker
---
@ynov

Intro
---
I'd like to share how to comfortably use essential Unix commands on Windows and how to bring the similar Unix environment to Windows based on my experience. Unix commands are known to be very handy and portable, but not really _portable_ if you use Windows, and there are ways to use those commands on Windows and each of them has its own advantages and disadvantages.

Ready by
---
Should be ready by 18 January 2019

**Comment by wgao19** [comment]
Links
---
- [Slides](https://docs.google.com/presentation/d/1T26e8wewuYuTNsIBIMEJEn5BBbEcwLJYxzseo97udVc/edit?usp=sharing)
