### ISSUE TITLE
⛰️ Piece Table

### ISSUE THREAD

**Issue by kenrick95** [Shopee/react-knowledgeable#64]
Speaker
---
@kenrick95 

Intro
---

I encountered this topic on late November 2017, and started making slides for a sharing, but it was abandoned since I never "won" any sharing slot till mid 2018, which by then there were already other more interesting topics to share.

So this concept is the "secret" of many popular text editors so that editors can run efficiently.

Ready by
---

WIP, still a lot of content to put in, let's say end Jan 2018?

**Comment by wgao19** [comment]
Sounds good. Will look forward to getting back from you later this month.

**Comment by wgao19** [comment]
Hi @kenrick95 how is this going?

**Comment by kenrick95** [comment]
Ah sorry, haven't had much progress on this ._.

**Comment by kenrick95** [comment]
Just an update, this should be ready for dry run; but since then, I've been cutting a lot of content that it might end up being a lighting talk 🙈

**Comment by wgao19** [comment]
That's OK. Let's do it next week?

**Comment by kenrick95** [comment]
Sure! Thanks for the patience 😹

**Comment by wgao19** [comment]
No worries! Scheduled you in :]

**Comment by kenrick95** [comment]
[Slides](https://docs.google.com/presentation/d/1CuoIo-r7JiVqaQBEICWweFYBCf1p-12jvlkMzzoBCfc/edit?usp=sharing)
