### ISSUE TITLE
React Knowledgeable #16 - Feb 1, 2019

### ISSUE THREAD

**Issue by KenLSM** [Shopee/react-knowledgeable#68]
🗓 Date: 18:00, Friday, Feb 1, 2019
🗺 Location: 2nd Floor Sharing Space

## ⛰️ The beautify things in Nintendo Gameboy #43

> Look into the design of the Nintendo Gameboy. Discover how the Gameboy hardware was designed, and admire the progress that technology have made.

## Call for Paper

We're calling for paper for Feb 22 (2nd week after CNY).

Nearest open dry run spot on Feb 15.

**Comment by wgao19** [comment]
Hi @KenLSM I wonder if you have this video on our YouTube channel yet and if so, would you please add the link here?
