### ISSUE TITLE
⛰️ Type safety at runtime

### ISSUE THREAD

**Issue by Cryrivers** [Shopee/react-knowledgeable#69]
Speaker
---
Zhongliang Wang (@Cryrivers )

Intro
---

Type safety at runtime, more from a developer experience perspective.

Ready by
---
Feb 1

**Comment by wgao19** [comment]
Hey @Cryrivers I remember you spoke about a book on type system in this talk. Can I ask again what it is?

**Comment by Cryrivers** [comment]
TypeScript Language Specification 1.6

https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md

**Comment by wgao19** [comment]
Thanks!
