### ISSUE TITLE
React Hooks ⛰️

### ISSUE THREAD

**Issue by tanhauhau** [Shopee/react-knowledgeable#73]
Speaker
---
@tanhauhau 

Intro
---
Things you need to know about React Hooks. This talk covers enough ideas and concept for you to understand how hook works, and to see why people are hyped about hooks.

Ready by
---
Ready

Slides
---
https://slides.com/tanhauhau/react-hook

**Comment by wgao19** [comment]
@tanhauhau dry run tmr?

**Comment by tanhauhau** [comment]
ok can. what time?

**Comment by wgao19** [comment]
> ok can. what time?

5pm as usual :)
