### ISSUE TITLE
Development of Web Development: JS Modules

### ISSUE THREAD

**Issue by tanhauhau** [Shopee/react-knowledgeable#83]
- Haven't figured out the length of the talk 😓 

Speaker
---
@tanhauhau 

Intro
---
A brief history of JavaScript modules, (from my perspective as a frontend developer a few years ago, highly opinionated), way before webpack or any bundlers is popular.

Ready by
---
4th April

**Comment by wgao19** [comment]
[slides](https://slides.com/tanhauhau/deck-9#/), consider updating the slides title man.
