### ISSUE TITLE
How to contribute to Open Source⚡️

### ISSUE THREAD

**Issue by tanhauhau** [Shopee/react-knowledgeable#93]
Speaker
---

@tanhauhau 

Intro
---

In Shopee, we use a lot of open source libraries, from UI libraries eg React, React Native, redux to dev tools, eg: webpack, babel, flow, etc. While reaping the benefits when adopting the latest technology, due to the complexity of our codebase, we often encounter issues and bugs that no one has ever faced. 

If a bug has fixed by the community, thank them. If not, fix them.

Ready by
---
May 10

**Comment by wgao19** [comment]
@tanhauhau can prepare first, we'll slot you in once you're ready.

**Comment by tanhauhau** [comment]
Slides ready: https://slides.com/tanhauhau/contributing-to-open-source
for a lightning talk

**Comment by wgao19** [comment]
@KenLSM let's do this with one of the new joiner's talk

**Comment by wgao19** [comment]
Hi @tanhauhau  please take note that this talk is scheduled to go on June 7 :)

**Comment by tanhauhau** [comment]
Dry run this week?

**Comment by wgao19** [comment]
This week got board game so may not have chance for dry run.

**Comment by wgao19** [comment]
@tanhauhau  I think tomorrow (Wed) can join a dry run with Chenchen's one at 2:30pm.

**Comment by tanhauhau** [comment]
ok, i need to go to listen to Tzyinc's talk at 3pm

**Comment by wgao19** [comment]
@tanhauhau Dry run moved to 11am FYI

**Comment by wgao19** [comment]
[Slides](http://slides.com/tanhauhau/contributing-to-open-source#/)
