### ISSUE TITLE
React Hooks Show-and-Tell

### ISSUE THREAD

**Issue by wgao19** [Shopee/react-knowledgeable#97]
So we've merged React 16.8 to our codebase. Time to test your hooks skill for real. If you've done anything with hooks, please _show and tell_ us. 
It may come from any project, be it Shopee or your own project. Please use this thread for proposals :]

**Comment by wgao19** [comment]
I'll go first: Hooks + CSS variables dark mode theme for Gatsby sites

**Comment by tanhauhau** [comment]
Hooks visualiser (WIP) https://github.com/tanhauhau/react-hooks-visualiser, still working on it, hopefully in time for show and tell

**Comment by JennieJi** [comment]
We use hooks in a new admin system. What kind of proposals do u suggest to raise?

**Comment by wgao19** [comment]
@JennieJi like I created this using hooks, which hooks I use, any custom hooks implemented and how, etc.

**Comment by tanhauhau** [comment]
just like the codepen show and tell

**Comment by AdrielLimanthie** [comment]
@wgao19 @JennieJi I think I'll share about the Form Builder library from admin project

**Comment by JennieJi** [comment]
😢 find I will be on leave that week... you guys enjoy
